### ISSUE TITLE
 jodconverte가 플러그인을 호출할 수 없습니다.

### ISSUE THREAD

**Issue by RemixC** [ebandal/H2Orestart#8]
플러그인을 사용한 다음 jodconverter를 사용하여 로컬 LibreOffice가 .hwp 파일을 열 수 없도록 구성합니다. jodconverter가 플러그인을 호출할 수 없기 때문입니까?

**Comment by ebandal** [comment]
H2Orestart는 libreoffice에 설치하는 플러그인 입니다. 먼저 libreoffice에  H2Orestart를 수동으로 설치해야합니다. Jodconverter는 플러그인을 호출할수 없습니다.

**Comment by OctopusET** [comment]
I think you should open an issue in the jodconverter main repo.

And could you share an error if there's any.

**Comment by RemixC** [comment]
java.lang.NullPointerException: Could not open document: 02JK5ke1wDGJ000_유사시 연락처.hwp
	at org.jodconverter.core.util.AssertUtils.notNull(AssertUtils.java:132) ~[jodconverter-core-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:210) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) [jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) [jodconverter-core-4.4.6.jar:4.4.6] @OctopusET

**Comment by RemixC** [comment]
java.lang.NullPointerException: Could not open document: 111.hwp
	at org.jodconverter.core.util.AssertUtils.notNull(AssertUtils.java:132) ~[jodconverter-core-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:210) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) [jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) [jodconverter-core-4.4.6.jar:4.4.6] @OctopusET

**Comment by ebandal** [comment]
@RemixC
NullPointerException occurred from jodconverter, not from H2Orestart. 
You'd better file an issue report on jodconverter.
For your information,  below command can be used in order LibreOffice to create PDF file for hwp file. 
$ soffice.exe" --headless --infilter="Hwp2002_Reader" --convert-to pdf:writer_pdf_Export 111.hwp
H2Orestart extension should be installed in advance. otherwise libreoffice will not recognize H2p2002_Reader fileter.

I'm not sure whether JodConverter internally uses command like above or not. 
You can also ask to JodConverter, not to H2Orestart.

**Comment by ebandal** [comment]
Not much detail information on reported issue. 
Given information, It seemed JodConveter issue, not H2Orestart related. 
So closing issue.
